### PR TITLE
Issue #487: Duplicatation and remote debuging

### PR DESCRIPTION
**Pull request by juherr**
I reported changes from #487 that could be useful

### CODE REVIEW

**Comment by cbeust** [comment]
Can you elaborate on the "debugging the remote mode" part?

**Comment by juherr** [comment]
Not at all! I've just wanted to close #487 which was not good enough and mixed to many things. Maybe @markshao could help.

**Comment by cbeust** [comment]
@juherr What's the status on this, should I close it without merging it?

**Comment by juherr** [comment]
We can, I will cherry pick 60e6821 later

**Pull request closed without merging**
