### PR TITLE
Bugfix/2267 retry with dp when configuring retry analyzer on config method

### LINKED ISSUE #2267: RetryAnalyzer is not set properly and consistent when using dataprovider
Hi folks,

I've encountered a little bug when using a custom `RetryAnalyzer` and a `DataProvider`  or the `Parameter`-Annotation.

### TestNG Version
7.1.0 - And current `master`-branch.

### Description
I will provide the code that leads to the "error", but at first I want to describe it.

When using the data provider and a custom `RetryAnalyzer` that is added in a `beforeInvocation`-method in an implementation of the `IInvokedMethodListener`-interface, the `RetryAnalyzer` is not added to the internal / private map `m_testMethodToRetryAnalyzer` in the following case:

When you call a `getRetryAnalyzer(testResult)` before a `setRetryAnalyzerClass(RetryIfFailed.class)` this error will occur, because the `computeIfAbsent`-call will return the default `DisabledRetryAnalyzer` instead of the new one that was added in ` beforeInvocation`.

### Expected behavior
The call of `getRetryAnalyzer(iTestResult)` should not affect the `setRetryAnalyzerClass` when using a Data Provider.

### Actual behavior
The call of `getRetryAnalyzer(iTestResult)` affects the `setRetryAnalyzerClass` when using a Data Provider.

### Is the issue reproductible on runner?

- [ ] Shell (not tested)
- [x] Maven
- [x] Gradle
- [ ] Ant (not tested)
- [ ] Eclipse (not tested)
- [x] IntelliJ
- [ ] NetBeans (not tested)

### Test case sample

.CustomerListener
````
public class CustomListener implements IInvokedMethodListener {

    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {

        if (method.isTestMethod()) {

            final IRetryAnalyzer currentRetryAnalyzer = method.getTestMethod().getRetryAnalyzer(testResult);

            // only override default retry analyzer but never a retry analyzer that may was added by another method call.
            if (currentRetryAnalyzer == null || currentRetryAnalyzer instanceof DisabledRetryAnalyzer) {
                method.getTestMethod().setRetryAnalyzerClass(RetryIfFailed.class);
                // this method here should as well respect the parameterbased setup that will be used for getting the current retry analyzer
            }
        }
    }
}
````

.RetryIfFailed RetryAnalyzer
````
public class RetryIfFailed implements IRetryAnalyzer {

    @Override
    public boolean retry(ITestResult result) {

        return !result.isSuccess();
    }
}
````

.RetryTest
````
@Listeners(CustomListener.class)
public class TestNgRetryTest {

    private static int counter = 0;

    @DataProvider(name = "dp")
    public Object[][] dp() {
        return new Object[][]{
                {1},
        };
    }

    @Test(dataProvider = "dp")
    public void testWithRetryAndDataProvider(int testNumber) {

        counter++;

        System.out.println("Data Provider: " + testNumber);
        System.out.println("Counter: " + counter);

        if (counter < 3) {
            Assert.fail("Counter is lower than 3: " + counter);
        }
    }
}
````

So executing this example will lead to a NON-Retry of my test method `testWithRetryAndDataProvider`. But when removing the `getRetryAnalyzer(testResult)` of my `CustomListener` class the test will be retried, because the internal map is filled correctly.

If I should add any value to this issue, please let me know.
Further I will create a pull request for the bug fix, if you appreciate it.

Best regards
Eric

### PR DESCRIPTION
**Pull request by erickubenka**
Fixes #2267 .

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

### CODE REVIEW

**Comment by erickubenka** [comment]
oh meh - i used wrong identation - what are you using?
spaces / tabs? how many?

**Comment by krmahadevan** [comment]
@erickubenka - We use the google formatter. Its spaces and not tabs. Can you please fix the formatting and update the PR ?

Oh btw, I noticed that you didn't add your name in the CHANGES.txt. Please do so. After all you are volunteering to spend your time to fix a bug in an open source project. Nothing wrong in calling it out.

**Comment by erickubenka** [comment]
> @erickubenka - We use the google formatter. Its spaces and not tabs. Can you please fix the formatting and update the PR ?
> 
> Oh btw, I noticed that you didn't add your name in the CHANGES.txt. Please do so. After all you are volunteering to spend your time to fix a bug in an open source project. Nothing wrong in calling it out.

Ah, spaces should be fixed now, but i guess, that line endings do not match. Will try to fix this as well.

**Comment by krmahadevan** [comment]
@erickubenka - It still shows a lot of changes in `/BaseTestMethod.java` class. Can you please try doing the following:

1. Take a copy of your changes for the particular method in question and keep it aside.
2. Amend your commit and exclude `BaseTestMethod.java` and commit your changes.
3. Now freshly apply your local changes again onto `BaseTestMethod.java` (Make sure you don't do a format of the entire java class, but just select your method and only format your changes) and create a new commit.
4. Now squash both the commits into one commit. 

That should fix this properly.

**Comment by erickubenka** [comment]
> @erickubenka - It still shows a lot of changes in `/BaseTestMethod.java` class. Can you please try doing the following:
> 
> 1. Take a copy of your changes for the particular method in question and keep it aside.
> 2. Amend your commit and exclude `BaseTestMethod.java` and commit your changes.
> 3. Now freshly apply your local changes again onto `BaseTestMethod.java` (Make sure you don't do a format of the entire java class, but just select your method and only format your changes) and create a new commit.
> 4. Now squash both the commits into one commit.
> 
> That should fix this properly.

Don't get it. On local machine in IntelliJ eyerything seems the same, no diffs. In Visual Studio Code the same. Dont get how to fix this.

**Comment by erickubenka** [comment]
> > @erickubenka - It still shows a lot of changes in `/BaseTestMethod.java` class. Can you please try doing the following:
> > 
> > 1. Take a copy of your changes for the particular method in question and keep it aside.
> > 2. Amend your commit and exclude `BaseTestMethod.java` and commit your changes.
> > 3. Now freshly apply your local changes again onto `BaseTestMethod.java` (Make sure you don't do a format of the entire java class, but just select your method and only format your changes) and create a new commit.
> > 4. Now squash both the commits into one commit.
> > 
> > That should fix this properly.
> 
> Don't get it. On local machine in IntelliJ eyerything seems the same, no diffs. In Visual Studio Code the same. Dont get how to fix this.

Even if I copy the code from github.com online editor from cbeust/testng/master branch into the github.com online editor for my branch there will show me the message, that contents are identical. 

Can you try to clone / check it out and check it locally? @krmahadevan

**Pull request closed without merging**
