### PR TITLE
add GitHub Actions ci workflow

### PR DESCRIPTION
**Pull request by sullis**
Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by krmahadevan** [comment]
@sullis - It would be great if you could please help add some context behind this PR.
From my limited understanding, it looks like github actions is something similar to what Travis CI (which is what currently TestNG uses) is doing. Is that a fair understanding ?

**Comment by krmahadevan** [comment]
@juherr your thoughts ?

**Comment by cbeust** [comment]
I'd like to proceed carefully with Github Actions since a lot of these actions are implemented by third parties (not Github) and using their actions means exposing private environment variables to these unknown entities.

**Comment by juherr** [comment]
IMO, GitHub actions could be a good move but we should remove Travis in that case.

For a more complete sample, have a look at https://github.com/raphw/byte-buddy/blob/master/.github/workflows/main.yml

@sullis Could you try to provide a full replacement of our travis build file? https://github.com/cbeust/testng/blob/master/.travis.yml

**Comment by cbeust** [comment]
Wait, before we go there, is there anything that Github Actions does that
Travis doesn't?

Is there a point in switching at all?

-- 
Cédric

**Comment by juherr** [comment]
2 features I see: full github integration (see https://github.com/raphw/byte-buddy/actions) and windows support as target.

It is difficult to compare github actions and travis: travis only runs scripts and github actions is a collection of tasks.

**Comment by krmahadevan** [comment]
@juherr - Do you think we can close this issue off now since we are now using GitHub actions to basically do our CI and also for our releases ?

**Comment by juherr** [comment]
Fixed

**Pull request closed without merging**
