### PR TITLE
Fix for 566 and refactoring around Invoker

### PR DESCRIPTION
**Pull request by VladRassokhin**
See commits messages

### CODE REVIEW

**Comment by blagae** [comment]
Hi Vlad,

I conversed about this fix with Cédric, and he said he needs your input on the pull request. Could you check your e-mail account ? I'll resend the mails to you, because they probably ended up in your spam filter or something.

Thanks,
Benoit

**Comment by cbeust** [comment]
I just tried this fix and it's causing a few tests to fail:

```
   [testng] ===============================================
   [testng] TestNG
   [testng] Total tests run: 609, Failures: 7, Skips: 0
   [testng] ===============================================
````

Because this PR has a lot of commits, identifying the culprit won't be trivial.

**Comment by cbeust** [comment]
Actually never mind, I was able to merge Vlad's PR into master.

**Comment by VladRassokhin** [comment]
@blagae there's nothing even in spam folder. Looks like gmail problem, will change public available email address. Resend to vlad.rassokhin@gmail.com, please.
@cbeust thanks for merging!

**Comment by blagae** [comment]
I can confirm that #566 is fixed in cbeust:master

**Pull request merged**
