### PR TITLE
Fix #686 IAnnotationTransformer.transform is called for methods with testClass populated

### LINKED ISSUE #686: IAnnotationTransformer.transform is called for methods with testClass populated
It seems that since e7eac6a (issue #87), JDK15AnnotationFinder always calls transformers with testClass populated in spite of the documentation:

https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/IAnnotationTransformer.java#L16-L22

### PR DESCRIPTION
**Pull request by juherr**

### CODE REVIEW

**Comment by cbeust** [comment]
Looks good, can you update the CHANGES file?

**Comment by juherr** [comment]
@cbeust Done with eb7327c3af30fb21ca9238da86377011ab3a253d, but I pushed into the wrong repository by error. Sorry! :(

**Comment by cbeust** [comment]
Do you need anything from me or is it fixed?

**Comment by juherr** [comment]
No, everything should be fixed.

**Pull request merged**
