### PR TITLE
Fixing Reporter.getOutput for ITestResult.

### PR DESCRIPTION
**Pull request by jsdevel**
* Before it was never storing log entries against an ITestResult.  getOutput would create a new List every time.

### CODE REVIEW

**Comment by juherr** [comment]
@jsdevel Why did you close the PR?

**Comment by jsdevel** [comment]
@juherr sorry.  I did a force push on a reset trying to test the build.

I'm actually having trouble running the tests locally.  Is there a contributor guide on doing this?

**Comment by juherr** [comment]
The best way to test is to follow the process from https://github.com/cbeust/testng/blob/master/build-with-maven
But it should work from your IDE too.

**Comment by jsdevel** [comment]
I'm getting this when trying to run them:

```
The build could not read 1 project -> [Help 1]
  
  The project org.testng:testng:6.8.22-SNAPSHOT (/home/joseph/projects/testng/pom.xml) has 1 error
    Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:3 from/to nexus (http://localhost:8081/nexus/content/groups/public): Connection to http://localhost:8081 refused and 'parent.relativePath' points at wrong local POM @ line 35, column 11: Connection refused -> [Help 2]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by jsdevel** [comment]
Do I need to be running nexus locally?

**Comment by jsdevel** [comment]
Running nexus locally got me further!  I moved `pom-test.xml` to `pom.xml` and now tests are running!  I should reopen shortly.

**Comment by juherr** [comment]
It should work without local nexus because Maven download artifact from maven central by default.
If you use an http proxy and/or settings.xml that overrides maven default, it could explain your problem.

You could register your fork on [travis](https://travis-ci.org) too, and it will run the test for you ;)

**Comment by juherr** [comment]
Moved to #660

**Pull request closed without merging**
