### PR TITLE
 #1673 enable generateTestResultAttributes using Maven

### LINKED ISSUE #1673: how to enable generateTestResultAttributes using Maven
6.13.1

### Expected behavior
testresult attributes should be present in the XML report

### Actual behavior
there are no testresult attributes present in the XML report

### Is the issue reproductible on runner?

- [ ] Shell
- [x ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

How can I setup TestNG, using Maven, for setting up the generateTestResultAttributes flag to true?
I tried several ways but I was unable to set it up; i'm unsure if there is a bug or not.
In my pom.xml I added this kind of config:
```xml
    <build>
        <plugins>
....
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>2.12.4</version>
        <configuration>
          <properties>
            <property>
              <name>usedefaultlisteners</name>
              <value>flase</value> <!-- disabling default listeners is optional -->
            </property>
             <property>
              <name>generateTestResultAttributes</name>
              <value>true</value>
            </property>
            <property>
              <name>reporter</name>
              <value>org.testng.reporters.XMLReporter</value>
            </property>
          </properties>
        </configuration>
      </plugin>
```

### PR DESCRIPTION
**Pull request by Kanaduchi**
Fixes #1673 enable generateTestResultAttributes using Maven

Did you remember to?
[*] Fix test case(s)
[] Update CHANGES.txt
We encourage pull requests that:

Add new features to TestNG (or)
Fix bugs in TestNG
If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the
TestNG-dev before you spend time working on it.

### CODE REVIEW

**Comment by madhura-75** [comment]
Hi I am still facing issue on this. I am not able to view attributes in testng xml report. Can you please guide me?

**Comment by krmahadevan** [comment]
@madhura-75 - You would need to be a bit more elaborate. How about you share a simple sample project that can be used to reproduce the problem and then post it on the TestNG users mailing list https://groups.google.com/g/testng-users

**Comment by madhura-75** [comment]
Hi Krishnan,

I am unable to display attributes like labels, Xraytest key id, requirement
id in my testng xml report, I need to import this report to Xray . Can you
please help me with this. It's been 5 days I am not able to figure out what
is the issue.  Below is a code of my test automation.

pom.xml

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>EPOSMobileTestFramework</groupId>
  <artifactId>MobileTestFramework</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>MobileTestFramework</name>
  
  <url>http://www.example.com</url>

  <properties>

  

        
        
       <xray.projectKey>CALC</xray.projectKey>

        


<xray.surefire.location>${basedir}/target/surefire-reports</xray.surefire.location>
        

  </properties>

  <dependencies>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>

    <dependency>
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>7.5.1</version>
    </dependency>

    <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.141.59</version>
    </dependency>

    <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.4.0</version>
    <scope>test</scope>
    </dependency>

    <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.30</version>
    <scope>test</scope>
    </dependency>

    <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.30</version>
    </dependency>

    <dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.12.0</version>
    </dependency>

    <dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.8.0</version>
    </dependency>

    <dependency>
    <groupId>commons-validator</groupId>
    <artifactId>commons-validator</artifactId>
    <version>1.7</version>
    </dependency>

    <dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.1.5</version>
    </dependency>

    <dependency>
    <groupId>com.googlecode.json-simple</groupId>
    <artifactId>json-simple</artifactId>
    <version>1.1.1</version>
    </dependency>


      <dependency>
          <groupId>app.getxray</groupId>
          <artifactId>xray-testng-extensions</artifactId>
          <version>0.2.0-beta</version>
          <scope>test</scope>
        </dependency>

   <dependency>
    <groupId>app.getxray</groupId>
    <artifactId>xray-maven-plugin</artifactId>
    <version>0.7.3</version>
</dependency>

  </dependencies>




    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <debug>true</debug>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20.1</version>

                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>

                    <suiteXmlFiles>
                      <suiteXmlFile>testng.xml</suiteXmlFile>
                    </suiteXmlFiles>

                    <properties>
                        <property>
                            <name>reporter</name>

<value>org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true</value>
                        </property>
                    </properties>

                </configuration>
             </plugin>




        </plugins>
    </build>

     <reporting>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-report-plugin</artifactId>
            </plugin>
        </plugins>
    </reporting>


</project>


testng.xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite" thread-count="5" verbose="10">
<listeners>
<listener
class-name="EPOSMobileTestFramework.MobileTestFramework.XrayListener"/>

</listeners>
  <test thread-count="5" name="Test">
    <classes>
      <class
name="EPOSMobileTestFramework.MobileTestFramework.PairingTestCases"/>



    </classes>
  </test> 
</suite> 


Same java code

@Test (priority = 1)
    @XrayTest(key = "CALC-1", labels="launch")
    @Requirement(key = "CALC-0001")
public void TES_31953() throws InterruptedException, IOException {


LaunchScreen ls = new LaunchScreen(driver);
DeviceScanScreen dss = new DeviceScanScreen(driver);

CommonObjects cObj = new CommonObjects(driver);


Thread.sleep(6000);
ls.termCondObj.click();
ls.allowDataObj.click();

ls.contObj.click();
Thread.sleep(3000);

try {
if(ls.grntLocObj.isDisplayed()) {
ls.grntLocObj.click();
ls.allowObj.click();
}
} catch (Exception e){
    ls.GrantPermissionObj.click();
ls.AllowOnceObj.click();

}




ls.contObj.click();
    Thread.sleep(5000);

}

Can you please check and let me know what wrong I am doing.


Thanks

**Comment by krmahadevan** [comment]
@madhura-75 - How about you share a simple sample project (either as a zip file or upload the sample into github and share a link of that project) that can be used to reproduce the problem and then post it on the TestNG users mailing list https://groups.google.com/g/testng-users

Let's not hijack this Pull Request comments for user support.

**Pull request closed without merging**
