### PR TITLE
Removing the prefix “m_” from data members.

### PR DESCRIPTION
**Pull request by krmahadevan**
Fixes # .

### Did you remember to?

- [ ] Add test case(s)
- [ ] Update `CHANGES.txt`

### CODE REVIEW

**Comment by krmahadevan** [comment]
@cbeust and @juherr - Please let me know if this can be merged. Since the changes are a lot, I will do this in phases if you folks are fine with this delivery. If not, I will skip the rest of it.

**Comment by juherr** [comment]
LGTM! 👍 IMO, it's a step forward and it will stop to burn my eyes :p 
BTW, I'm not sure @cbeust will approve too ;p

**Comment by krmahadevan** [comment]
@juherr - My humble apologies. I thought I had already ran the unit tests locally before I raised the PR. Guess I didnt... *embarrassed*

Please give me sometime. Will take care of this once I reach home. 

Once again, my apologies for the confusion.

**Comment by juherr** [comment]
@krmahadevan No prob, don't worry!

**Comment by krmahadevan** [comment]
Closing this PR.

**Pull request closed without merging**
