### PR TITLE
Fix assert message in assert API

### LINKED ISSUE #2118: Default assertion message
It would be nice to provide some default messages when no mssage is provided, instead of showing:
```
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.assertNotEquals(Assert.java:1157)
	at org.testng.Assert.assertNotEquals(Assert.java:1162)
```

For this example the Object::toString method could be used to output "%s not equals %s", ex:
```
    public static void assertNotEquals(Object actual1, Object actual2) {
        String message = String.format( "%s not equals %s", actual1, actual2 );
        assertNotEquals(actual1, actual2, message);
    }
```
Similar to other methods where no message is provided.

TestNG 6.14.3

### PR DESCRIPTION
**Pull request by jiong-fu**
Fixes #2118 .

### Did you remember to?

- [x] Add test case(s)
- [x] Update `CHANGES.txt`

We encourage pull requests that:

* Add new features to TestNG (or)
* Fix bugs in TestNG

If your pull request involves fixing SonarQube issues then we would suggest that you please discuss this with the 
[TestNG-dev](https://groups.google.com/forum/#!forum/testng-dev) before you spend time working on it.

### CODE REVIEW

**Comment by jiong-fu** [comment]
It has been tricky somehow because of the default assert message. Hope I have got it right with this pull request.

**Comment by krmahadevan** [comment]
@jiong-fu 

From your dev branch, can you please share the output of the following tests here as a comment. That would add a bit more clarity. I would like to compare and contrast the two outputs

```java
import org.testng.Assert;
import org.testng.annotations.Test;

public class AssertSamples {

  @Test
  public void f1() {
    Assert.assertEquals(true, false);
  }

  @Test
  public void f2() {
    Assert.assertNotEquals(true, true);
  }

  @Test
  public void f3() {
    Object object = new Object();
    Assert.assertNotSame(object, object);
  }

  @Test
  public void f4() {
    Assert.fail();
  }

  @Test
  public void f5() {
    Assert.assertTrue(false);
  }

  @Test
  public void f6() {
    Assert.assertFalse(true);
  }

}
```

Here's the surefire execution output from `7.0.0`

```
[INFO] Running com.rationaleemotions.AssertSamples
[ERROR] Tests run: 6, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.399 s <<< FAILURE! - in com.rationaleemotions.AssertSamples
[ERROR] f1(com.rationaleemotions.AssertSamples)  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
        at com.rationaleemotions.AssertSamples.f1(AssertSamples.java:10)

[ERROR] f2(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: did not expect to find [true] but found [true]
        at com.rationaleemotions.AssertSamples.f2(AssertSamples.java:15)

[ERROR] f3(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected not same [java.lang.Object@185d8b6] but found [java.lang.Object@185d8b6]
        at com.rationaleemotions.AssertSamples.f3(AssertSamples.java:21)

[ERROR] f4(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: null
        at com.rationaleemotions.AssertSamples.f4(AssertSamples.java:26)

[ERROR] f5(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: did not expect to find [true] but found [false]
        at com.rationaleemotions.AssertSamples.f5(AssertSamples.java:31)

[ERROR] f6(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: did not expect to find [false] but found [true]
        at com.rationaleemotions.AssertSamples.f6(AssertSamples.java:36)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AssertSamples.f1:10 expected [false] but found [true]
[ERROR]   AssertSamples.f2:15 did not expect to find [true] but found [true]
[ERROR]   AssertSamples.f3:21 expected not same [java.lang.Object@185d8b6] but found [java.lang.Object@185d8b6]
[ERROR]   AssertSamples.f4:26 null
[ERROR]   AssertSamples.f5:31 did not expect to find [true] but found [false]
[ERROR]   AssertSamples.f6:36 did not expect to find [false] but found [true]
[INFO] 
[ERROR] Tests run: 6, Failures: 6, Errors: 0, Skipped: 0

```

**Comment by jiong-fu** [comment]
> @jiong-fu
> 
> From your dev branch, can you please share the output of the following tests here as a comment. That would add a bit more clarity. I would like to compare and contrast the two outputs
> 
> ```java
> import org.testng.Assert;
> import org.testng.annotations.Test;
> 
> public class AssertSamples {
> 
>   @Test
>   public void f1() {
>     Assert.assertEquals(true, false);
>   }
> 
>   @Test
>   public void f2() {
>     Assert.assertNotEquals(true, true);
>   }
> 
>   @Test
>   public void f3() {
>     Object object = new Object();
>     Assert.assertNotSame(object, object);
>   }
> 
>   @Test
>   public void f4() {
>     Assert.fail();
>   }
> 
>   @Test
>   public void f5() {
>     Assert.assertTrue(false);
>   }
> 
>   @Test
>   public void f6() {
>     Assert.assertFalse(true);
>   }
> 
> }
> ```
> 
> Here's the surefire execution output from `7.0.0`
> 
> ```
> [INFO] Running com.rationaleemotions.AssertSamples
> [ERROR] Tests run: 6, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.399 s <<< FAILURE! - in com.rationaleemotions.AssertSamples
> [ERROR] f1(com.rationaleemotions.AssertSamples)  Time elapsed: 0.015 s  <<< FAILURE!
> java.lang.AssertionError: expected [false] but found [true]
>         at com.rationaleemotions.AssertSamples.f1(AssertSamples.java:10)
> 
> [ERROR] f2(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
> java.lang.AssertionError: did not expect to find [true] but found [true]
>         at com.rationaleemotions.AssertSamples.f2(AssertSamples.java:15)
> 
> [ERROR] f3(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
> java.lang.AssertionError: expected not same [java.lang.Object@185d8b6] but found [java.lang.Object@185d8b6]
>         at com.rationaleemotions.AssertSamples.f3(AssertSamples.java:21)
> 
> [ERROR] f4(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
> java.lang.AssertionError: null
>         at com.rationaleemotions.AssertSamples.f4(AssertSamples.java:26)
> 
> [ERROR] f5(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
> java.lang.AssertionError: did not expect to find [true] but found [false]
>         at com.rationaleemotions.AssertSamples.f5(AssertSamples.java:31)
> 
> [ERROR] f6(com.rationaleemotions.AssertSamples)  Time elapsed: 0 s  <<< FAILURE!
> java.lang.AssertionError: did not expect to find [false] but found [true]
>         at com.rationaleemotions.AssertSamples.f6(AssertSamples.java:36)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   AssertSamples.f1:10 expected [false] but found [true]
> [ERROR]   AssertSamples.f2:15 did not expect to find [true] but found [true]
> [ERROR]   AssertSamples.f3:21 expected not same [java.lang.Object@185d8b6] but found [java.lang.Object@185d8b6]
> [ERROR]   AssertSamples.f4:26 null
> [ERROR]   AssertSamples.f5:31 did not expect to find [true] but found [false]
> [ERROR]   AssertSamples.f6:36 did not expect to find [false] but found [true]
> [INFO] 
> [ERROR] Tests run: 6, Failures: 6, Errors: 0, Skipped: 0
> ```

@krmahadevan I'm not sure how to generate the surefire report, therefore I just copy paste the shortened execution output from IntelliJ console.
```
java.lang.AssertionError: expected [false] but found [true]

java.lang.AssertionError: did not expect [true] but found [true]

java.lang.AssertionError: expected not same [java.lang.Object@72d818d1] but found [java.lang.Object@72d818d1]

java.lang.AssertionError: null

java.lang.AssertionError: expected [true] but found [false]

java.lang.AssertionError: expected [false] but found [true]

===============================================
My_Suite
Total tests run: 6, Passes: 0, Failures: 6, Skips: 0
===============================================
```

**Comment by krmahadevan** [comment]
@jiong-fu - The output from both the runs look the same. So I am trying to understand what changed. Can you please me understand that

**Comment by jiong-fu** [comment]
@krmahadevan to resolve the issue #2080, I replaced the beginning message 'did not expect to find' with 'did expect', so that the assertion message in assertTrue / assertFalse works correctly. However, the change affected also assertNotEquals, since it uses the beginning message internally. Consequentlly, with the actual master branch the default message would be for example 'did expect [true] but found [true]' which is misleading.

**Comment by jiong-fu** [comment]
@krmahadevan The most important part in the pull request is
https://github.com/cbeust/testng/pull/2133/files#diff-079c4701a6752e4bec03337f0aeb8ba9R969
There are two cases to consider - 
1. asserted **equal** but the actual outcome is **not equal** -> true should be passed to the format method -> the assert message should be the form 'expected A but found B'
2. asserted **not equal** but the actual outcome is **equal** -> false should be passed to the format method -> the assert message should be the form 'did not expect A but found A'

**Comment by krmahadevan** [comment]
@jiong-fu Which issue are we fixing with this PR ?

Is it #2118 ( which talks about adding a default message for assertions ) or #2080 ?

If it's #2118 then I don't think we fixed the ask in the bug in this PR no ( that's why I asked for a comparative output )

**Comment by jiong-fu** [comment]
@krmahadevan Good question, it is my fault. With this pull request still only the old problem can be fixed. So I now start working on the real issue, may I then put everything together in one pull request?

**Comment by krmahadevan** [comment]
@jiong-fu - Sure. Please feel free to close this PR, and open it back when you are ready.

> With this pull request still only the old problem can be fixed. So I now start working on the real issue,

So does it mean you would be fixing #2118  (or) #2080 ? Please do clarify that when you open up a new PR, because your updates to `CHANGES.txt` says its fixing #2118 I am just trying to ensure that I have a good understanding of what we are fixing.

**Comment by jiong-fu** [comment]
@krmahadevan Thanks for the tips. With the changes in this pull request the #2080 should be fixed and it remains to open another pull request to track the changes. What I am going to fix is the #2118.

**Pull request closed without merging**
