### PR TITLE
Fix same ITestListener being added multiple times

### LINKED ISSUE #956: ITestListener's methods get called multiple times for one test, when there are multiple tests in the xml
Similar to #171, this applies to ITestListener instances.

When there are multiple <xmlfileset> and the xmls all use the same test listener, onFinish() gets called multiple times for one test, which does not seem intended.

### PR DESCRIPTION
**Pull request by LibertyLocked**
Should fix #956

### CODE REVIEW

**Comment by cbeust** [comment]
This PR appears to break a lot of things:

https://travis-ci.org/cbeust/testng/jobs/102675818

**Comment by LibertyLocked** [comment]
My apologies. Obviously I didn't test it.
I'll look into this. Thank you

**Comment by cbeust** [comment]
Thanks! Also, it would be great if you could add a test for your change...


-- 
Cédric

**Comment by dr29bart** [comment]
Please, close the PR since related issues are not reproducible in 6.10

**Pull request closed without merging**
