### PR TITLE
Fix #onAssertSuccess called after #onAssertFailure in SoftAssert

### PR DESCRIPTION
**Pull request by VladRassokhin**
Improve failure message in SoftAssert#assertAll

BTW. Another approach is do not throw exception in Assertion#doAssert, but do that in #onAssertFailure. But that is API change.

### CODE REVIEW

**Comment by juherr** [comment]
:+1:

**Comment by cbeust** [comment]
FYI, one of the tests is failing, looking into it.

**Comment by juherr** [comment]
Do you want I have a look? Or maybe @VladRassokhin could?

**Comment by cbeust** [comment]
Go ahead, @juherr, I'm being sidetracked right now.

**Comment by juherr** [comment]
@cbeust I have no failed test :]

I propose we continue on #741

**Comment by VladRassokhin** [comment]
Finally, it's merged :)

**Comment by cbeust** [comment]
@VladRassokhin, you have @juherr to thank and me to mock :)

**Comment by juherr** [comment]
Thank to https://youtrack.jetbrains.com/issue/IDEA-145327 I've just realized that this changes introduced an issue (see #784).

I can reproduce the issue by updating `testAssertAllCount` test with `sa.assertTrue(false, "My message")` which will produce:

```
The following asserts failed:
	My message	My message expected [true] but found [false]
```

The test is still ok but `My message` is duplicated.

Currently, I don't know how to fix it.

**Pull request closed without merging**
